add wave -position insertpoint  \
sim:/tb_f2_dsp/reset_clock_div \
sim:/tb_f2_dsp/reset_loop \
sim:/tb_f2_dsp/lane_refclk_reset \
sim:/tb_f2_dsp/io_lanes_tx_enq_clock \
sim:/tb_f2_dsp/io_lanes_rx_deq_clock \
sim:/tb_f2_dsp/reset \
sim:/tb_f2_dsp/io_ctrl_and_clocks_tx_reset_clkdiv \
sim:/tb_f2_dsp/io_ctrl_and_clocks_rx_reset_clkdiv \
sim:/tb_f2_dsp/io_ctrl_and_clocks_reset_dacfifo \
sim:/tb_f2_dsp/io_ctrl_and_clocks_reset_dacfifo \
sim:/tb_f2_dsp/io_ctrl_and_clocks_reset_adcfifo \
sim:/tb_f2_dsp/io_ctrl_and_clocks_reset_outfifo \
sim:/tb_f2_dsp/io_ctrl_and_clocks_reset_infifo \
sim:/tb_f2_dsp/io_iptr_A_0_real \
sim:/tb_f2_dsp/io_Z_0_real_t \
sim:/tb_f2_dsp/io_Z_0_real_b \
sim:/tb_f2_dsp/io_lanes_rx_0_bits_data_0_udata_real \
sim:/tb_f2_dsp/io_lanes_rx_0_bits_data_0_udata_imag \
sim:/tb_f2_dsp/io_lanes_tx_0_bits_data_0_udata_real \
sim:/tb_f2_dsp/io_lanes_tx_0_bits_data_0_udata_imag \
sim:/tb_f2_dsp/clock \
sim:/tb_f2_dsp/lane_refclk \
sim:/tb_f2_dsp/io_clkp2n \
sim:/tb_f2_dsp/io_clkp4n \
sim:/tb_f2_dsp/io_clkp8n \
sim:/tb_f2_dsp/f2_dsp/f2_tx_dsp/io_iptr_A_bits_data_0_udata_real \
sim:/tb_f2_dsp/f2_dsp/f2_tx_dsp/f2_tx_path/f2_interpolator/io_iptr_A_real \
sim:/tb_f2_dsp/f2_dsp/f2_tx_dsp/f2_tx_path/f2_interpolator/reset \
sim:/tb_f2_dsp/f2_dsp/f2_tx_dsp/f2_tx_path/f2_interpolator/io_clocks_cic3clockfast \
sim:/tb_f2_dsp/f2_dsp/f2_tx_dsp/f2_tx_path/f2_interpolator/io_clocks_hb1clock_low \
sim:/tb_f2_dsp/f2_dsp/f2_tx_dsp/f2_tx_path/f2_interpolator/io_clocks_hb1clock_high \
sim:/tb_f2_dsp/f2_dsp/f2_tx_dsp/f2_tx_path/f2_interpolator/io_clocks_hb2clock_high \
sim:/tb_f2_dsp/f2_dsp/f2_tx_dsp/f2_tx_path/f2_interpolator/io_clocks_hb3clock_high \
sim:/tb_f2_dsp/f2_dsp/f2_tx_dsp/f2_tx_path/f2_interpolator/io_controls_cic3derivscale \
sim:/tb_f2_dsp/f2_dsp/f2_tx_dsp/f2_tx_path/f2_interpolator/io_controls_cic3derivshift \
sim:/tb_f2_dsp/f2_dsp/f2_tx_dsp/f2_tx_path/f2_interpolator/io_controls_reset_loop \
sim:/tb_f2_dsp/f2_dsp/f2_tx_dsp/f2_tx_path/f2_interpolator/io_iptr_A_real \
sim:/tb_f2_dsp/f2_dsp/f2_tx_dsp/f2_tx_path/f2_interpolator/io_iptr_A_imag \
sim:/tb_f2_dsp/f2_dsp/f2_tx_dsp/f2_tx_path/f2_interpolator/io_Z_real \
sim:/tb_f2_dsp/f2_dsp/f2_tx_dsp/f2_tx_path/f2_interpolator/io_Z_imag \
sim:/tb_f2_dsp/f2_dsp/f2_tx_dsp/f2_tx_path/f2_interpolator/hb1_io_iptr_A_real \
sim:/tb_f2_dsp/f2_dsp/f2_tx_dsp/f2_tx_path/f2_interpolator/hb1_clock \
sim:/tb_f2_dsp/f2_dsp/f2_tx_dsp/f2_tx_path/f2_interpolator/hb1_reset \
sim:/tb_f2_dsp/f2_dsp/f2_tx_dsp/f2_tx_path/f2_interpolator/hb2_clock \
sim:/tb_f2_dsp/f2_dsp/f2_tx_dsp/f2_tx_path/f2_interpolator/hb2_reset \
sim:/tb_f2_dsp/f2_dsp/f2_tx_dsp/f2_tx_path/f2_interpolator/hb2_io_clock_high \
sim:/tb_f2_dsp/f2_dsp/f2_tx_dsp/f2_tx_path/f2_interpolator/hb2_io_scale \
sim:/tb_f2_dsp/f2_dsp/f2_tx_dsp/f2_tx_path/f2_interpolator/hb2_io_iptr_A_real \
sim:/tb_f2_dsp/f2_dsp/f2_tx_dsp/f2_tx_path/f2_interpolator/hb2_io_iptr_A_imag \
sim:/tb_f2_dsp/f2_dsp/f2_tx_dsp/f2_tx_path/f2_interpolator/hb2_io_Z_real \
sim:/tb_f2_dsp/f2_dsp/f2_tx_dsp/f2_tx_path/f2_interpolator/hb3_clock \
sim:/tb_f2_dsp/f2_dsp/f2_tx_dsp/f2_tx_path/f2_interpolator/hb3_reset \
sim:/tb_f2_dsp/f2_dsp/f2_tx_dsp/f2_tx_path/f2_interpolator/hb3_io_clock_high \
sim:/tb_f2_dsp/f2_dsp/f2_tx_dsp/f2_tx_path/f2_interpolator/hb3_io_iptr_A_real \
sim:/tb_f2_dsp/f2_dsp/f2_tx_dsp/f2_tx_path/f2_interpolator/hb3_io_Z_real \
sim:/tb_f2_dsp/f2_dsp/f2_tx_dsp/f2_tx_path/f2_interpolator/cic3_clock \
sim:/tb_f2_dsp/f2_dsp/f2_tx_dsp/f2_tx_path/f2_interpolator/cic3_reset \
sim:/tb_f2_dsp/f2_dsp/f2_tx_dsp/f2_tx_path/f2_interpolator/cic3_io_clockfast \
sim:/tb_f2_dsp/f2_dsp/f2_tx_dsp/f2_tx_path/f2_interpolator/cic3_io_derivscale \
sim:/tb_f2_dsp/f2_dsp/f2_tx_dsp/f2_tx_path/f2_interpolator/cic3_io_derivshift \
sim:/tb_f2_dsp/f2_dsp/f2_tx_dsp/f2_tx_path/f2_interpolator/cic3_io_iptr_A_real \
sim:/tb_f2_dsp/f2_dsp/f2_tx_dsp/f2_tx_path/f2_interpolator/cic3_io_Z_real \
sim:/tb_f2_dsp/f2_dsp/f2_tx_dsp/f2_tx_path/io_dsp_ioctrl_dac_data_mode \
sim:/tb_f2_dsp/f2_dsp/f2_tx_dsp/f2_tx_path/io_dac_clock \
sim:/tb_f2_dsp/f2_dsp/f2_tx_dsp/f2_tx_path/io_clock_symrate \
sim:/tb_f2_dsp/f2_dsp/f2_tx_dsp/f2_tx_path/io_iptr_A_0_real \
sim:/tb_f2_dsp/f2_dsp/f2_tx_dsp/f2_tx_path/io_iptr_A_0_imag \
sim:/tb_f2_dsp/f2_dsp/f2_tx_dsp/f2_tx_path/daclut_real__T_2194_addr \
sim:/tb_f2_dsp/f2_dsp/f2_tx_dsp/f2_tx_path/daclut_imag__T_2195_addr \
sim:/tb_f2_dsp/f2_dsp/f2_tx_dsp/f2_tx_path/r_lutoutdata_real \
sim:/tb_f2_dsp/f2_dsp/f2_tx_dsp/f2_tx_path/r_lutoutdata_imag \
sim:/tb_f2_dsp/f2_dsp/f2_tx_dsp/f2_tx_path/r_lutreadaddress_real \
sim:/tb_f2_dsp/f2_dsp/f2_tx_dsp/f2_tx_path/r_lutreadaddress_imag \
sim:/tb_f2_dsp/f2_dsp/f2_tx_dsp/f2_tx_path/r_lutreadaddress_imag \
sim:/tb_f2_dsp/f2_dsp/f2_tx_dsp/f2_tx_path/r_lutreadaddress_real \
sim:/tb_f2_dsp/f2_dsp/f2_tx_dsp/f2_tx_path/r_lutreadaddress_imag \
sim:/tb_f2_dsp/f2_dsp/f2_tx_dsp/f2_tx_path/AsyncQueue_io_enq_bits_real_b \
sim:/tb_f2_dsp/f2_dsp/f2_tx_dsp/f2_tx_path/AsyncQueue_io_enq_bits_real_t \
sim:/tb_f2_dsp/f2_dsp/f2_tx_dsp/f2_tx_path/AsyncQueue_io_enq_bits_imag_b \
sim:/tb_f2_dsp/f2_dsp/f2_tx_dsp/f2_tx_path/AsyncQueue_io_enq_bits_imag_t \
sim:/tb_f2_dsp/f2_dsp/f2_tx_dsp/f2_tx_path/AsyncQueue_io_deq_bits_real_b \
sim:/tb_f2_dsp/f2_dsp/f2_tx_dsp/f2_tx_path/AsyncQueue_io_deq_bits_real_t \
sim:/tb_f2_dsp/f2_dsp/f2_tx_dsp/f2_tx_path/AsyncQueue_io_deq_bits_imag_b \
sim:/tb_f2_dsp/f2_dsp/f2_tx_dsp/f2_tx_path/AsyncQueue_io_deq_bits_imag_t \
sim:/tb_f2_dsp/f2_dsp/f2_serdes_test/io_scan_write_en \
sim:/tb_f2_dsp/f2_dsp/f2_serdes_test/io_scan_write_mode \
sim:/tb_f2_dsp/f2_dsp/f2_serdes_test/io_scan_write_address \
sim:/tb_f2_dsp/f2_dsp/f2_serdes_test/io_scan_read_mode \
sim:/tb_f2_dsp/f2_dsp/f2_serdes_test/io_scan_read_address \
sim:/tb_f2_dsp/f2_dsp/f2_serdes_test/io_scan_write_mode \
sim:/tb_f2_dsp/f2_dsp/f2_serdes_test/io_scan_write_address \
sim:/tb_f2_dsp/f2_dsp/f2_serdes_test/io_from_serdes_ready \
sim:/tb_f2_dsp/f2_dsp/f2_serdes_test/io_from_serdes_valid \
sim:/tb_f2_dsp/io_ctrl_and_clocks_serdestest_scan_read_value_data_0_udata_real \
sim:/tb_f2_dsp/io_ctrl_and_clocks_serdestest_scan_read_value_data_0_udata_imag \
sim:/tb_f2_dsp/io_ctrl_and_clocks_serdestest_scan_write_value_data_0_udata_real \
sim:/tb_f2_dsp/io_ctrl_and_clocks_serdestest_scan_write_value_data_0_udata_imag \
sim:/tb_f2_dsp/f2_dsp/f2_serdes_test/io_from_serdes_bits_data_0_udata_real \
sim:/tb_f2_dsp/f2_dsp/f2_serdes_test/io_from_serdes_bits_data_0_udata_imag \
sim:/tb_f2_dsp/io_ctrl_and_clocks_dsp_to_serdes_address_0 \
sim:/tb_f2_dsp/io_ctrl_and_clocks_dsp_to_serdes_address_1 \
sim:/tb_f2_dsp/io_ctrl_and_clocks_dsp_to_serdes_address_2 \
sim:/tb_f2_dsp/io_ctrl_and_clocks_dsp_to_serdes_address_3 \
sim:/tb_f2_dsp/io_ctrl_and_clocks_serdes_to_dsp_address_0 \
sim:/tb_f2_dsp/io_ctrl_and_clocks_serdes_to_dsp_address_1 \
sim:/tb_f2_dsp/io_ctrl_and_clocks_serdes_to_dsp_address_2 \
sim:/tb_f2_dsp/io_ctrl_and_clocks_serdes_to_dsp_address_3 \
sim:/tb_f2_dsp/io_ctrl_and_clocks_serdes_to_dsp_address_4 \
sim:/tb_f2_dsp/io_ctrl_and_clocks_serdes_to_dsp_address_5 \
sim:/tb_f2_dsp/f2_dsp/f2_serdes_test/memblock_clock \
sim:/tb_f2_dsp/f2_dsp/f2_serdes_test/memblock_reset \
sim:/tb_f2_dsp/f2_dsp/f2_serdes_test/memblock_io_write_addr \
sim:/tb_f2_dsp/f2_dsp/f2_serdes_test/memblock_io_read_addr \
sim:/tb_f2_dsp/f2_dsp/f2_serdes_test/memblock_io_read_val_data_0_udata_real \
sim:/tb_f2_dsp/f2_dsp/f2_serdes_test/memblock_io_read_val_data_0_udata_imag \
sim:/tb_f2_dsp/f2_dsp/f2_serdes_test/memblock_io_write_val_data_0_udata_real \
sim:/tb_f2_dsp/f2_dsp/f2_serdes_test/memblock_io_write_val_data_0_udata_imag \
sim:/tb_f2_dsp/f2_dsp/f2_serdes_test/memblock/mem_proto_data_0_udata_real \
sim:/tb_f2_dsp/f2_dsp/f2_serdes_test/memblock/mem_proto_data_0_udata_imag \
sim:/tb_f2_dsp/f2_dsp/f2_serdes_test/AsyncQueue/io_enq_clock \
sim:/tb_f2_dsp/f2_dsp/f2_serdes_test/AsyncQueue/io_enq_reset \
sim:/tb_f2_dsp/f2_dsp/f2_serdes_test/AsyncQueue/io_enq_ready \
sim:/tb_f2_dsp/f2_dsp/f2_serdes_test/AsyncQueue/io_enq_valid \
sim:/tb_f2_dsp/f2_dsp/f2_serdes_test/AsyncQueue/io_deq_clock \
sim:/tb_f2_dsp/f2_dsp/f2_serdes_test/AsyncQueue/io_deq_reset \
sim:/tb_f2_dsp/f2_dsp/f2_serdes_test/AsyncQueue/io_deq_ready \
sim:/tb_f2_dsp/f2_dsp/f2_serdes_test/AsyncQueue/io_deq_valid \
sim:/tb_f2_dsp/f2_dsp/f2_serdes_test/AsyncQueue_1/io_enq_clock \
sim:/tb_f2_dsp/f2_dsp/f2_serdes_test/AsyncQueue_1/io_enq_reset \
sim:/tb_f2_dsp/f2_dsp/f2_serdes_test/AsyncQueue_1/io_enq_ready \
sim:/tb_f2_dsp/f2_dsp/f2_serdes_test/AsyncQueue_1/io_enq_valid \
sim:/tb_f2_dsp/f2_dsp/f2_serdes_test/AsyncQueue_1/io_deq_clock \
sim:/tb_f2_dsp/f2_dsp/f2_serdes_test/AsyncQueue_1/io_deq_reset \
sim:/tb_f2_dsp/f2_dsp/f2_serdes_test/AsyncQueue_1/io_deq_ready \
sim:/tb_f2_dsp/f2_dsp/f2_serdes_test/AsyncQueue_1/io_deq_valid \
sim:/tb_f2_dsp/f2_dsp/f2_serdes_test/edge_detector/io_A \
sim:/tb_f2_dsp/f2_dsp/f2_serdes_test/edge_detector/io_rising \
sim:/tb_f2_dsp/f2_dsp/f2_serdes_test/edge_detector_1/io_A \
sim:/tb_f2_dsp/f2_dsp/f2_serdes_test/edge_detector_1/io_rising \
sim:/tb_f2_dsp/f2_dsp/f2_serdes_test/edge_detector_2/io_A \
sim:/tb_f2_dsp/f2_dsp/f2_serdes_test/edge_detector_2/io_rising \
sim:/tb_f2_dsp/f2_dsp/f2_serdes_test/edge_detector_3/io_A \
sim:/tb_f2_dsp/f2_dsp/f2_serdes_test/edge_detector_3/io_rising \
sim:/tb_f2_dsp/f2_dsp/f2_lane_switch/io_to_dsp_5_ready \
sim:/tb_f2_dsp/f2_dsp/f2_lane_switch/io_to_dsp_5_valid \
sim:/tb_f2_dsp/f2_dsp/f2_lane_switch/io_from_serdes_0_valid \
sim:/tb_f2_dsp/f2_dsp/f2_lane_switch/io_from_serdes_0_bits_data_0_udata_real \
sim:/tb_f2_dsp/f2_dsp/f2_lane_switch/io_from_serdes_0_bits_data_0_udata_imag \
sim:/tb_f2_dsp/f2_dsp/f2_serdes_test/io_from_serdes_ready \
sim:/tb_f2_dsp/f2_dsp/f2_serdes_test/io_from_serdes_valid \
sim:/tb_f2_dsp/f2_dsp/f2_serdes_test/AsyncQueue_io_deq_ready \
sim:/tb_f2_dsp/f2_dsp/f2_serdes_test/AsyncQueue_io_deq_valid 

